import sys
sys.path.insert(0, '.')
from normalizers.cpu import build_product_key
samples = [
"PROCESADOR AMD RYZEN 7 7800X3D 5.0GHZ TURBO AM5 - NO INCLUYE COOLER",
"PROCESADOR AMD RYZEN 7 5700G 4.6GHZ TURBO AM4 + WRAITH STEALTH COOLER",
"PROCESADOR AMD RYZEN 7 5700X 4.6GHZ TURBO AM4 - NO INCLUYE COOLER",
"PROCESADOR AMD RYZEN 5 5500 4.2GHZ TURBO AM4 + WRAITH STEALTH COOLER",
"PROCESADOR AMD RYZEN 7 9800X3D 5.0GHZ TURBO AM5 - NO INCLUYE COOLER",
"MICRO AMD ATHLON 3000G 3.5GHZ AM4",
]
for s in samples:
    print(s)
    print('->', build_product_key(s))
